"""
This module contains indexing constants for the four rooms project.

Author: Hannah Sheahan, sheahan.hannah@gmail.com
Date: 25/11/2019
"""

# Constants for session indexing.
SESSION_TRAINING, SESSION_SCANNER = range(2)

# Game FSM state constants.
STATE_STARTSCREEN, STATE_SETUP, STATE_BLANKSCREEN,STATE_STARTTRIAL,STATE_GOALAPPEAR,\
STATE_DELAY,STATE_GO,STATE_MOVING1,STATE_SHOWREWARD, STATE_STAR1FOUND, STATE_MOVING2,\
STATE_STAR2FOUND, STATE_FINISH, STATE_NEXTTRIAL, STATE_INTERTRIAL, STATE_TIMEOUT,\
STATE_ERROR, STATE_REST, STATE_GETREADY, STATE_PAUSE, STATE_HALLFREEZE, STATE_DEBRIEF,\
STATE_EXIT,STATE_MAX = range(24)
